### PR TITLE
Fix rounding

### PR DESCRIPTION
**Pull request by changyaochen**
* Major style formatting, change tabs to 4 space, and PEP8 + google style
* add a function to bound the return values between [0, 1]

### CODE REVIEW

**Review by f4lco — CHANGES_REQUESTED** [review]
Looks good to me 👍 Just two suggestions you may consider:

If settled for a coding style, it would be good to document which one it is, like in the readme. Ideally, there also would be an automated way to check it. Just like a sentence, "make sure to run [pycodestyle](https://github.com/PyCQA/pycodestyle), [pydocstyle](https://github.com/PyCQA/pydocstyle), or [yapf](https://github.com/google/yapf), before committing".

Concerning `_bound_range`: I would consider adding an assertion prior to "adjusting" the value. Similar to:

```python
assert 0 <= rbo <= 1 or np.isclose(1, rbo)
```

This way, we detect if the rbo computation went entirely off the rails, or if we are still processing a legit value. Without the assertion, bugs might go unnoticed.

**Comment by f4lco** [comment]
Also, my prior comment implies the following: I assume there is no need to guard against values below zero. If I understood the computation of average overlap (and the resulting RBO) correctly, the following holds: starting at zero similarity, the set intersection algorithm determines, if there is no overlap, or if the element was common to the two lists. Only in the latter case, we add a positive increment to the similarity, I suppose. As a result, there should not be a case where rounding error leads to a computation result below zero.

**Comment by changyaochen** [comment]
Thanks for the good comments. I agree that that should be a clear style guide (currently I'm using the google style [here](http://google.github.io/styleguide/pyguide.html) -- there is no right answer to which style is the right style, but one just needs to pick one... I somewhat got stuck with google style...

With that said, it would be nice to run the code checker... maybe make it as a feature request?

As for the `_bound_range`, I was thinking just to use it on the "safe" side, since by definition, the return value should be bounded between [0. and 1.], so let's just make sure it is the case. My guess for any return value that is outside this range is a rounding issue, which can be safely round to either 0 or 1. Therefore, this `_bound_range` function should only be effective in those cases...

**Comment by f4lco** [comment]
> With that said, it would be nice to run the code checker... maybe make it as a feature request?

Yes, this sounds perfectly reasonable. You may create a ticket for this :)

> My guess for any return value that is outside this range is a rounding issue, which can be safely round to either 0 or 1. Therefore, this _bound_range function should only be effective in those cases...

This is... likely what I was trying to say. To my opinion, a method for correcting a rounding error could consist of (1) verifying if this is indeed a rounding error (sanity check) and (2) finally correct it. Compare: 

```python
In [7]: def _bound_range(value):
   ...:     assert np.isclose(0, value) or 0 <= value <= 1 or np.isclose(1, value), "This is not a rounding error"
   ...:     larger_than_zero = max(0.0, value)
   ...:     less_than_one = min(1.0, larger_than_zero)
   ...:     return less_than_one
In [8]: [_bound_range(x) for x in [0, 0.5, 1, 1 + 1e-10, -1e-10]]  # valid inputs
Out[8]: [0.0, 0.5, 1.0, 1.0, 0.0]
In [9]: _bound_range(3.14)  # is not a valid RBO value and is not a rounding error -> AssertionError
```
But anyway, it's a minor issue. I'll leave it to you - please decide yourself and merge at will 👍

**Review by f4lco — APPROVED** [review]

**Comment by changyaochen** [comment]
I add a try/except to handle the bound_range. Will merge the PR.

**Pull request merged**
